### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by johntranz** [mayanbhadage/sign_language_recognition#1]
https://github.com/mayanbhadage/sign_language_recognition/blob/269c4b2e77287ec01a003730e38f7fa23c6d329c/generate_hand_histogram.py#L127

--> `print('{}Histogram genetated.{}'.format(colors.CBOLD, colors.CEND))`

**Comment by mayanbhadage** [comment]
Hey Jane-Tran,

Thanks for going through the code. I think that syntax is correct in Python 3. Let me know if you still face any issues

**Comment by johntranz** [comment]
Thanks for the reply.
I also just deep learning. My project is great, I try to experiment to learn more
I had an error while developing my friend.
`  File "generate_hand_histogram.py", line 39, in calculate_histogram
    hsv = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`
I have a fix for this. That is a must `image != None`
![Screenshot from 2020-05-08 22-11-13](https://user-images.githubusercontent.com/44759245/81419810-105fb700-9179-11ea-9309-b62dcb357d50.png)
But it doesn't work the same as what you described.
Please tell me where I was wrong

**Comment by mayanbhadage** [comment]
I have never faced this issue maybe because you are using different versions of OpenCV try to make the virtual environment as described in Readme. And let me know if you face the same error
